### PR TITLE
Added entry property to events.

### PR DESCRIPTION
**Pull request by jaydensmith**
Added entry property to OnBeforePopulateEntryEvent and OnBeforeValidateEntryEvent. The event's aren't very useful without access to the entry.

### CODE REVIEW

**Comment by BenParizek** [comment]
@jayden I'm comfortable adding this to the `OnBeforeValidateEntryEvent` but I'm hesitant to add it to the `OnBeforePopulateEntryEvent` as the whole point of that event was to be fired before the entry got populated so a field could manipulate something in the POST request to prepare it before it was added to the Entry Model and validated. 

Do you have a use case where you feel you need the Entry Model available to you on an event before the `OnBeforeValidateEntryEvent`?

**Comment by jaydensmith** [comment]
Hey @BenParizek, I'm more concerned with the `OnBeforeValidateEntryEvent` event, as I just need to do some more conditional validation on entries, for which I need to be able to access the entry itself.

**Comment by BenParizek** [comment]
Thanks for this pull request @jaydensmith.

I'm closing it out but will be adding the $entry event to the OnBeforeValidateEntryEvent.

See here for any additional comments: 
https://github.com/barrelstrength/craft-sprout-forms/issues/324

**Comment by BenParizek** [comment]
@jaydensmith This has been added in the latest release: Sprout Forms v3.4.0

**Pull request closed without merging**
