### PR TITLE
Fixed status filter

### PR DESCRIPTION
**Pull request by jaydensmith**
The entry status filter on the entry element index page doesn't work due to searching the `status` criteria. This fixes that and also fixes the status colour which was causing additional issues.

I've also added some template hooks, I hope you'll consider adding those.

### CODE REVIEW

**Comment by BenParizek** [comment]
Thanks @jaydensmith - I've got a busy week with travel this week but will review. 

Could you give me an example or two of how you would like to use the Template Hooks? Happy to consider adding them, just want to understand how they can be used better.

**Comment by jaydensmith** [comment]
Hey @BenParizek, I have a custom module that allows form submissions to be published to certain entries. The client wants a shortcut to do this in the entry details panel.

**Comment by andrelopez** [comment]
Thanks @jaydensmith we'll back to you if we have any questions

**Comment by BenParizek** [comment]
@jaydensmith 

We've modified a few things about the implementation but the latest release of Sprout Forms (v3.4.3) includes both of these updates (fixes to the status behavior and the new template hooks).

In the future, if you could separate distinct features into separate PRs it'd be appreciated. That helps us evaluate each PR individually as we sometimes have to reconcile a few things about how a PR works with the larger application structure.

In any case, thanks for the PR and glad we could get all these items into the plugin!

**Comment by jaydensmith** [comment]
Yeah no worries @BenParizek, thanks for your efforts.

**Pull request merged**
